create table config(name varchar,value varchar);
create table mst_group(guid varchar,name varchar,parent varchar,primary_group varchar,is_revenue tinyint,is_deemedpositive tinyint,is_reserved tinyint,affects_gross_profit tinyint,sort_position int);
create table mst_ledger(guid varchar,name varchar,parent varchar,alias varchar,description varchar,notes varchar,is_revenue tinyint,is_deemedpositive tinyint,opening_balance decimal(17,2),closing_balance decimal(17,2),mailing_name varchar,mailing_address varchar,mailing_state varchar,mailing_country varchar,mailing_pincode varchar,email varchar,it_pan varchar,gstn varchar,gst_registration_type varchar,gst_supply_type varchar,gst_duty_head varchar,tax_rate decimal(9,4),bank_account_holder varchar,bank_account_number varchar,bank_ifsc varchar,bank_swift varchar,bank_name varchar,bank_branch varchar,bill_credit_period int);
create table mst_vouchertype(guid varchar,name varchar,parent varchar,numbering_method varchar,is_deemedpositive tinyint,affects_stock tinyint);
create table mst_uom(guid varchar,name varchar,formalname varchar,is_simple_unit tinyint,base_units varchar,additional_units varchar,conversion decimal(15,4) int);
create table mst_godown(guid varchar,name varchar,parent varchar,address varchar);
create table mst_stock_category(guid varchar,name varchar,parent varchar);
create table mst_stock_group(guid varchar,name varchar,parent varchar);
create table mst_stock_item(guid varchar,name varchar,parent varchar,category varchar,alias varchar,description varchar,notes varchar,part_number varchar,uom varchar,alternate_uom varchar,conversion decimal(15,4) int,opening_balance decimal(15,4),opening_rate decimal(15,4),opening_value decimal(17,2),closing_balance decimal(15,4),closing_rate decimal(15,4),closing_value decimal(17,2),costing_method varchar,gst_type_of_supply varchar,gst_hsn_code varchar,gst_hsn_description varchar,gst_rate decimal(9,4),gst_taxability varchar);
create table mst_cost_category(guid varchar,name varchar,allocate_revenue tinyint,allocate_non_revenue tinyint);
create table mst_cost_centre(guid varchar,name varchar,parent varchar,category varchar);
create table mst_attendance_type(guid varchar,name varchar,parent varchar,uom varchar,attendance_type varchar,attendance_period varchar);
create table mst_employee(guid varchar,name varchar,parent varchar,id_number varchar,date_of_joining date,date_of_release date,designation varchar,function_role varchar,location varchar,gender varchar,date_of_birth date,blood_group varchar,father_mother_name varchar,spouse_name varchar,address varchar,mobile varchar,email varchar,pan varchar,aadhar varchar,uan varchar,pf_number varchar,pf_joining_date date,pf_relieving_date date,pr_account_number varchar);
create table mst_payhead(guid varchar,name varchar,parent varchar,payslip_name varchar,pay_type varchar,income_type varchar,calculation_type varchar,leave_type varchar,calculation_period varchar);
create table mst_gst_effective_rate(item varchar,applicable_from date,hsn_description varchar,hsn_code varchar,rate decimal(9,4),is_rcm_applicable tinyint,nature_of_transaction varchar,nature_of_goods varchar,supply_type varchar,taxability varchar);
create table mst_opening_batch_allocation(name varchar,item varchar,opening_balance decimal(15,4),opening_rate decimal(15,4),opening_value decimal(17,2),godown varchar,manufactured_on date);
create table mst_opening_bill_allocation(ledger varchar,opening_balance decimal(17,4),bill_date date,name varchar,bill_credit_period int,is_advance tinyint);
create table trn_closingstock_ledger(ledger varchar,stock_date date,stock_value decimal(17,2));
create table mst_stockitem_standard_cost(item varchar,date date,rate decimal(15,4));
create table mst_stockitem_standard_price(item varchar,date date,rate decimal(15,4));
create table trn_voucher(guid varchar,date date,voucher_type varchar,voucher_number varchar,reference_number varchar,reference_date date,narration varchar,party_name varchar,place_of_supply varchar,is_invoice tinyint,is_accounting_voucher tinyint,is_inventory_voucher tinyint,is_order_voucher tinyint);
create table trn_accounting(guid varchar,ledger varchar,amount decimal(17,2),amount_forex decimal(17,2),currency varchar);
create table trn_inventory(guid varchar,item varchar,quantity decimal(15,4),rate decimal(15,4),amount decimal(17,2),additional_amount decimal(17,2),discount_amount decimal(17,2),godown varchar,tracking_number varchar,order_number varchar,order_duedate date);
create table trn_cost_centre(guid varchar,ledger varchar,costcentre varchar,amount decimal(17,2));
create table trn_cost_category_centre(guid varchar,ledger varchar,costcategory varchar,costcentre varchar,amount decimal(17,2));
create table trn_cost_inventory_category_centre(guid varchar,ledger varchar,item varchar,costcategory varchar,costcentre varchar,amount decimal(17,2));
create table trn_bill(guid varchar,ledger varchar,name varchar,amount decimal(17,2),billtype varchar,bill_credit_period int);
create table trn_bank(guid varchar,ledger varchar,transaction_type varchar,instrument_date date,instrument_number varchar,bank_name varchar,amount decimal(17,2),bankers_date date);
create table trn_batch(guid varchar,item varchar,name varchar,quantity decimal(15,4),amount decimal(17,2),godown varchar,destination_godown varchar,tracking_number varchar);
create table trn_inventory_accounting(guid varchar,ledger varchar,amount decimal(17,2),additional_allocation_type varchar);
create table trn_employee(guid varchar,category varchar,employee_name varchar,amount decimal(17,2),employee_sort_order int);
create table trn_payhead(guid varchar,category varchar,employee_name varchar,employee_sort_order int,payhead_name varchar,payhead_sort_order int,amount decimal(17,2));
create table trn_attendance(guid varchar,employee_name varchar,attendancetype_name varchar,time_value decimal(17,2),type_value decimal(17,2));

copy mst_group from 'csv/mst_group.csv';
copy mst_ledger from 'csv/mst_ledger.csv';
copy mst_vouchertype from 'csv/mst_vouchertype.csv';
copy mst_uom from 'csv/mst_uom.csv';
copy mst_godown from 'csv/mst_godown.csv';
copy mst_stock_category from 'csv/mst_stock_category.csv';
copy mst_stock_group from 'csv/mst_stock_group.csv';
copy mst_stock_item from 'csv/mst_stock_item.csv';
copy mst_cost_category from 'csv/mst_cost_category.csv';
copy mst_cost_centre from 'csv/mst_cost_centre.csv';
copy mst_attendance_type from 'csv/mst_attendance_type.csv';
copy mst_employee from 'csv/mst_employee.csv';
copy mst_payhead from 'csv/mst_payhead.csv';
copy mst_gst_effective_rate from 'csv/mst_gst_effective_rate.csv';
copy mst_opening_batch_allocation from 'csv/mst_opening_batch_allocation.csv';
copy mst_opening_bill_allocation from 'csv/mst_opening_bill_allocation.csv';
copy trn_closingstock_ledger from 'csv/trn_closingstock_ledger.csv';
copy mst_stockitem_standard_cost from 'csv/mst_stockitem_standard_cost.csv';
copy mst_stockitem_standard_price from 'csv/mst_stockitem_standard_price.csv';
copy trn_voucher from 'csv/trn_voucher.csv';
copy trn_accounting from 'csv/trn_accounting.csv';
copy trn_inventory from 'csv/trn_inventory.csv';
copy trn_cost_centre from 'csv/trn_cost_centre.csv';
copy trn_cost_category_centre from 'csv/trn_cost_category_centre.csv';
copy trn_cost_inventory_category_centre from 'csv/trn_cost_inventory_category_centre.csv';
copy trn_bill from 'csv/trn_bill.csv';
copy trn_bank from 'csv/trn_bank.csv';
copy trn_batch from 'csv/trn_batch.csv';
copy trn_inventory_accounting from 'csv/trn_inventory_accounting.csv';
copy trn_employee from 'csv/trn_employee.csv';
copy trn_payhead from 'csv/trn_payhead.csv';
copy trn_attendance from 'csv/trn_attendance.csv';